export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="gruvbox"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(git dirhistory common-aliases command-not-found autojump npm virtualenv)
NPM_PACKAGES="${HOME}/.npm-packages"
export PATH="$HOME/bin:$NPM_PACKAGES/bin:$PATH"
unset MANPATH
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"
source $ZSH/oh-my-zsh.sh
export EDITOR='vim'
DISABLE_UPDATE_PROMPT=true
